### ISSUE TITLE
External file with content

### ISSUE THREAD

**Issue by pristis** [Honatas/bootstrap-4-autocomplete#17]
Hello!

Your autocomplete is awesome and works great!

But I have an issue that I can't handle. I want to load the data from external file somewhere on my server. Can you give me the advice how to do that?

Thank you!

**Comment by Honatas** [comment]
Hi @pristis.

This lib is not about loading data, you should have your data already loaded while invoking autocomplete. In a browser, you can achieve this with a simple ajax request.
