### ISSUE TITLE
How to make AJAX URL working with autocomplete

### ISSUE THREAD

**Issue by hirenaspl** [Honatas/bootstrap-4-autocomplete#2]
Hello @Honatas 

One more issue I'm facing ATM and would appreciate your help. I tried every way you mentioned at https://bootstrap-autocomplete.readthedocs.io/en/latest/ regarding how to make AJAX URL working with autocomplete but somehow that isn't helping. Can you please check and provide me some guidance about how to make it working. I've made a JSFiddle as well - https://jsfiddle.net/ae0o5fzy/.

Below is code I'm trying with:

```
$(this).autocomplete({
                resolverSettings: {
                    url: 'http://api.dev.phoenix.com/v1/en/users/autocomplete/email'
                },
                treshold: 2,
                onSelectItem: function(item, element) {
                    let input = $(element).data('value-input');
                    $('#'+input).val(item.value);
                }
            });
```

Please guide.

Many thanks,
Hiren

**Comment by Honatas** [comment]
Hi @hirenaspl .

You are looking at the documentation for another project. Please refer to the README here on GitHub or [npm](https://www.npmjs.com/package/bootstrap-4-autocomplete).

I don't have plans to directly invoke any url inside the lib. What you can do is set autocomplete to your textfield after your ajax call returns, which you can do with jQuery, like this:

`$.ajax('myurl').then((data) => $('#myTextfield').autocomplete({ source: data }));`

You don't have to worry about setting autocomplete to a field multiple times, it is supposed to work like this when you need to change the source.

**Comment by hirenaspl** [comment]
Hi @Honatas,

Thanks for suggestion. Eventually, I fallback to jQuery native autocomplete as I wasn't able to find some good solution for AJAX calls. Your library is great and would definitely serve the purpose for autocomplete where static options are involved. May be you can consider AJAX support later to enrich this.

Thanks for all help, guidance and support and I appreciate that you are very prompt.

Have a nice day.
