### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by cdalexndr** [Honatas/bootstrap-4-autocomplete#3]
Live demos will help attract more people

**Comment by Honatas** [comment]
Certainly they would. I've created a very simple example (that can be greatly improved) but it is not live yet. Any suggestions for hosting ?

**Comment by cdalexndr** [comment]
I think you can host directly on github: https://pages.github.com

**Comment by jsjunior** [comment]
Not much, but offer a general overview: 
[https://jsfiddle.net/0k8o2hrL/](url)

**Comment by marchao100** [comment]
Hi, I need to use your component for my final project, but the source has to be an array. Could this be possible? I was trying for hours but I don't get it. Thanks.

**Comment by cachecahce** [comment]
well i have copied/pasted the code on a test page https://bootstrap.controle-reglementaire.fr/test.html
autocomplete not working at all

**Comment by Honatas** [comment]
I've created a fiddle: [https://jsfiddle.net/Honatas/n943qob1/5/](https://jsfiddle.net/Honatas/n943qob1/5/)
