### ISSUE TITLE
How to use the autocomplete in a form context?

### ISSUE THREAD

**Issue by VILLAN3LL3** [Honatas/bootstrap-4-autocomplete#32]
I was wondering how to use your autocomplete field in a form context. Means: How to get the selected value of the autocomplate field when calling .serializeArray() of the form element and how to set the value when patching the form with stored values.
Thanks!

**Comment by Honatas** [comment]
The same way you would with any other input. Have in mind that for serializeArray() to work, you need to have set the 'name' attribute of your input.

**Comment by VILLAN3LL3** [comment]
Thank you for your answer. But this way only the label will be serialized, not the value

**Comment by Honatas** [comment]
Well, a label is one thing, a value is another and the id is even another. Anyway, that's how jQuery's serializeArray() works, and this has nothing to do with this lib. If you want another result, you should implement your own serialization.

**Comment by VILLAN3LL3** [comment]
Yes, but when using a dropdown we can pass an option label and value and serializeArray() will use the option value of the selected option. With this autocomplete control only the label is accessible.

**Comment by Honatas** [comment]
You have to implement the onSelectItem callback to get this value. I'd advise to set it to a hidden input on your form, and leave the autocomplete input without a name so it doesn't get serialized.
