### ISSUE TITLE
List not being hidden after selection

### ISSUE THREAD

**Issue by toby1kenobi** [Honatas/bootstrap-4-autocomplete#38]
Thanks for this component, it's really good. I have a weird issue - the autocomplete list appears ok, and when I select an item the text field is updated. The list itself is not disappearing though. Console isn't showing any errors, not sure how to debug?

**Comment by toby1kenobi** [comment]
Ah, I wonder if it's because I actally have Bootstrap 5?

**Comment by Honatas** [comment]
Yes, this lib doesn't work with Bootstrap 5.
