### ISSUE TITLE
Option to fetch source by ajax request

### ISSUE THREAD

**Issue by cdalexndr** [Honatas/bootstrap-4-autocomplete#5]
Looking for the following functionality:
1. User types text
2. Fetch request to server for autocomplete items
3. User types more text
4. Another fetch request for updated items

**Comment by leijae** [comment]
would love to have this,

**Comment by Honatas** [comment]
Since requests to any server which responds with data can be made in a wide variety of ways, I am not planning to include this feature on this lib. By doing so it would restrict how you would retrieve your data.
