### ISSUE TITLE
threshold not treshold

### ISSUE THREAD

**Issue by Fleshgrinder** [Honatas/bootstrap-4-autocomplete#7]
It’s [threshold](https://www.merriam-webster.com/dictionary/threshold) not _treshold_. ☺️

**Comment by Honatas** [comment]
Fact. But since the misspelling of this word is actually common, the impact of a correction will be bigger than the impact of leaving it as is, since it will not incur in misunderstanding of its functionality. Unfortunate, indeed.

**Comment by pierre-vr** [comment]
You could also use both for people willing to use the correct spelling.

**Comment by jpwilksch** [comment]
> You could also use both for people willing to use the correct spelling.

Agree. A correctly-spelled alias would be nice.
